apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: groups.k8sio.auth
spec:
  group: k8sio.auth
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              description: The specification of the Group.
              type: object
              properties:
                CRoles:
                  type: array
                  items:
                    type: object
                    properties:
                      namespace:
                        type: string
                      clusterRole:
                        type: string
                Roles:
                  type: array
                  items:
                     type: string
  scope: Namespaced
  names:
    kind: Group
    listKind: GroupList
    plural: groups
    singular: group
    categories:
      - idp
    shortNames:
      - grp
