apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: roles.k8sio.auth
spec:
  group: k8sio.auth
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
              - rules
              properties:
                rules:
                  type: array
                  items:
                    type: object
                    properties:
                      apiGroups:
                        type: array
                        items:
                          type: string
                      resources:
                        type: array
                        items:
                          type: string
                      verbs:
                        type: array
                        items:
                          type: string
  scope: Namespaced
  names:
    plural: roles
    singular: role
    kind: Role
    listKind: RoleList
    categories:
      - idp
    shortNames:
      - r
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterroles.k8sio.auth
spec:
  group: k8sio.auth
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
              - rules
              properties:
                rules:
                  type: array
                  items:
                    type: object
                    properties:
                      apiGroups:
                        type: array
                        items:
                          type: string
                      resources:
                        type: array
                        items:
                          type: string
                      verbs:
                        type: array
                        items:
                          type: string
                      resourceNames:
                        type: array
                        items:
                          type: string
  scope: Cluster
  names:
    plural: clusterroles
    singular: clusterrole
    kind: ClusterRole
    listKind: ClusterRoleList
    categories:
      - idp
    shortNames:
      - cr
