apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: users.k8sio.auth
spec:
  group: k8sio.auth
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              description: The specification of the user.
              type: object
              properties:
                enabled:
                  type: boolean
                CRoles:
                  type: array
                  items:
                    type: object
                    properties:
                      namespace:
                        type: string
                        minLength: 1
                      clusterRole:
                        type: string
                        minLength: 1
                      group:
                        type: string
                        minLength: 1
                    # Specify required fields within CRole
                    required:
                      - namespace
                      - clusterRole
                Roles:
                  type: array
                  items:
                     type: string
                     minLength: 1
  scope: Namespaced
  names:
    plural: users
    singular: user
    kind: User
    listKind: UserList
    categories:
      - idp
    shortNames:
      - usr
