apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-iam-operator
  namespace: iam
spec:
  selector:
    matchLabels:
      app: k8s-iam-operator
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-iam-operator
    spec:
      serviceAccountName: k8s-iam-operator
      containers:
      - name: k8s-iam-operator
        image: quay.io/yannick_siewe/k8s-iam-operator:latest
