apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-iam-operator.fullname" . }}
  labels:
    {{- include "k8s-iam-operator.labels" . | nindent 4 }}
data:
  GROUP_NAME: {{ .Values.config.groupName | quote }}
  VERSION: {{ .Values.config.version | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  ENABLE_TRACING: {{ .Values.tracing.enabled | quote }}
  {{- if .Values.tracing.enabled }}
  TEMPO_ENDPOINT: {{ .Values.tracing.endpoint | quote }}
  {{- end }}
  AUDIT_ENABLED: {{ .Values.audit.enabled | quote }}
